#!/usr/bin/env bash

setup_reflector() {
    sudo pacman -S reflector

    echo 'Getting fastest mirrors'
    sudo reflector --verbose --country 'United States' -l 20 -p https --sort rate --save /etc/pacman.d/mirrorlist

    sudo pacman -Syy
}

pacman_tweaks() {
    echo 'Enabling parallel downloads and colors'
    sudo sed -i '/Color/s/^#//' /etc/pacman.conf
    sudo sed -i '/Color/a ILoveCandy' /etc/pacman.conf
    sudo sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf
    sudo sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 25/g' /etc/pacman.conf

    sudo pacman -Syy
}

setup_paru() {
    echo 'Setting up Paru'
	sudo pacman -S --needed base-devel
	git clone https://aur.archlinux.org/paru.git
	cd paru
	makepkg -si

    echo 'Remove paru folder'
    cd ..
    rm -rf paru

    echo 'Update packages'
    paru -Syy
}

setup_hyprland() {
    echo 'Installing requested packages'
    paru -S acpilight \
	waybar \
    blueman \
    bluez \
    bluez-utils \
    chromium \
    foot \
    wireplumber \
    linux-headers \
    make \
    neofetch \
    nvidia-dkms \
    pamixer \
    pavucontrol \
    ttf-jetbrains-mono-nerd \
    ttf-nerd-fonts-symbols \
    xdg-user-dirs \
    playerctl \
    wget \
    nodejs \
    npm \
    power-profiles-daemon \
    noto-fonts-cjk \
    network-manager-applet \
    gvfs \
    xarchiver \
    mako \
    gnome-keyring \
    rust \
    rust-analyzer \
	hyprland \
	hyprpicker \
	nvidia-utils \
	sddm \
	hyprcursor \
	hyprgraphics \
	hypridle \
	hyprland-protocols \
	hyprland-qt-support \
	hyprland-qtutils \
	hyprlock \
	hyprpolkitagent \
	hyprshot \
	hyprsunset \
	hyprutils \
	hyprwayland-scanner \
	xdg-desktop-portal-hyprland \
	nautilus \
	gnome-themes-extra \
	libnvidia-egl-wayland \
	fuzzel \
	wofi \
	grim \
	swappy \
	slurp \

    echo 'Installing AUR packages'
    paru -S candy-icons-git \
    visual-studio-code-bin \

    echo 'Enabling services'
    sudo systemctl enable power-profiles-daemon.service
    sudo systemctl enable sddm.service
    sudo systemctl enable bluetooth.service

    echo 'Add user to wheel and video groups'
    sudo usermod -aG wheel $(whoami)
    sudo usermod -aG video $(whoami)

    echo 'Copying config files'
    cp -r ./foot ~/.config
    cp -r ./hypr ~/.config
    cp -r ./mako ~/.config
    cp -r ./waybar ~/.config
    cp -r ./nvim ~/.config
}

setup_kde() {
    echo 'Installing requested packages'
    paru -S chromium \
    linux-headers \
    make \
    ttf-nerd-fonts-symbols \
    wget \
    steam \
    nodejs \
    npm \
    noto-fonts-cjk \
    otf-monaspace-nerd \
    neovim \

    echo 'Installing AUR packages'
    paru -S visual-studio-code-bin

    echo 'Enabling services'
    sudo systemctl enable bluetooth.service

    echo 'Settings up neovim'
    cp -r ./nvim ~/.config
}

setup_gnome() {
    echo 'Installing requested packages'
    paru -S chromium \
    linux-headers \
    nvidia-dkms \
    ttf-nerd-fonts-symbols \
    otf-monaspace-nerd \
    wget \
    steam \
    nodejs \
    npm \
    noto-fonts-cjk \
    power-profiles-daemon \
    gnome-themes-extra \

    echo 'Installing AUR packages'
    paru -S visual-studio-code-bin \

    echo 'Enabling services'
    sudo systemctl enable bluetooth.service
    sudo systemctl enable power-profiles-daemon.service
}

setup_nvidia() {
    echo 'Setup nvidia.conf'
    sudo touch /etc/modprobe.d/nvidia.conf
    echo 'options nvidia-drm modeset=1' | sudo tee /etc/modprobe.d/nvidia.conf

    echo "Updating mkinitcpio config with nvidia"
    echo "
    MODULES=(btrfs nvidia nvidia_modeset nvidia_uvm nvidia_drm)
    BINARIES=(/usr/bin/btrfs)
    FILES=()
    HOOKS=(base udev autodetect keyboard keymap modconf block filesystems fsck)" | sudo tee /etc/mkinitcpio.conf
}

setup_bashrc() {
    echo 'Copy bash config'
    cp ./.bashrc ~/
}

main() {
    echo "Welcome to the setup script, lets get started!"

    read -p "Do you want to setup reflector (Y/N)?" reflector
    if [ $reflector == 'Y' ] || [ $reflector == 'y' ]; then
        setup_reflector
    fi

    read -p "Do you want to setup parallel downloads and colors (Y/N)?" pacman
    if [ $pacman == 'Y' ] || [ $pacman == 'y' ]; then
        pacman_tweaks
    fi

    read -p "Do you want to setup paru (Y/N)?" paru
    if [ $paru == 'Y' ] || [ $paru == 'y' ]; then
        setup_paru
    fi

    read -p "Do you want to setup hyprland (Y/N)?" hyprland
    if [ $hyprland == 'Y' ] || [ $hyprland == 'y' ]; then
        setup_hyprland
    fi

    read -p "Do you want to setup kde packages (Y/N)?" kde
    if [ $kde == 'Y' ] || [ $kde == 'y' ]; then
        setup_kde
    fi

    read -p "Do you want to setup gnome packages (Y/N)?" gnome
    if [ $gnome == 'Y' ] || [ $gnome == 'y' ]; then
        setup_gnome
    fi

    read -p "Do you want to setup nvidia drivers (Y/N)?" nvidia
    if [ $nvidia == 'Y' ] || [ $nvidia == 'y' ]; then
        setup_nvidia
    fi

    read -p "Do you want to setup bashrc (Y/N)?" bashrc
    if [ $bashrc == 'Y' ] || [ $bashrc == 'y' ]; then
        setup_bashrc
    fi
}

main











